/* File: dpresmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sat Jan 30 00:25:27 2021
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *dpres_error;
static PyObject *dpres_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(dpres_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = dpres_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = dpres_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** dpres1d **********************************/
static char doc_f2py_rout_dpres_dpres_dpres1d[] = "\
dpres1d(plevel,psfc,pmsg,ptop,dp,iopt,kflag,ier,[klvl])\n\nWrapper for ``dpres1d``.\
\n\nParameters\n----------\n"
"plevel : input rank-1 array('d') with bounds (klvl)\n"
"psfc : input float\n"
"pmsg : input float\n"
"ptop : input float\n"
"dp : input rank-1 array('d') with bounds (klvl)\n"
"iopt : input int\n"
"kflag : input int\n"
"ier : input int\n"
"\nOther Parameters\n----------------\n"
"klvl : input int, optional\n    Default: len(plevel)";
/*  */
static PyObject *f2py_rout_dpres_dpres_dpres1d(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,double*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int klvl = 0;
  PyObject *klvl_capi = Py_None;
  double *plevel = NULL;
  npy_intp plevel_Dims[1] = {-1};
  const int plevel_Rank = 1;
  PyArrayObject *capi_plevel_tmp = NULL;
  int capi_plevel_intent = 0;
  PyObject *plevel_capi = Py_None;
  double psfc = 0;
  PyObject *psfc_capi = Py_None;
  double pmsg = 0;
  PyObject *pmsg_capi = Py_None;
  double ptop = 0;
  PyObject *ptop_capi = Py_None;
  double *dp = NULL;
  npy_intp dp_Dims[1] = {-1};
  const int dp_Rank = 1;
  PyArrayObject *capi_dp_tmp = NULL;
  int capi_dp_intent = 0;
  PyObject *dp_capi = Py_None;
  int iopt = 0;
  PyObject *iopt_capi = Py_None;
  int kflag = 0;
  PyObject *kflag_capi = Py_None;
  int ier = 0;
  PyObject *ier_capi = Py_None;
  static char *capi_kwlist[] = {"plevel","psfc","pmsg","ptop","dp","iopt","kflag","ier","klvl",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|O:dpres.dpres.dpres1d",\
    capi_kwlist,&plevel_capi,&psfc_capi,&pmsg_capi,&ptop_capi,&dp_capi,&iopt_capi,&kflag_capi,&ier_capi,&klvl_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iopt */
    f2py_success = int_from_pyobj(&iopt,iopt_capi,"dpres.dpres.dpres1d() 6th argument (iopt) can't be converted to int");
  if (f2py_success) {
  /* Processing variable kflag */
    f2py_success = int_from_pyobj(&kflag,kflag_capi,"dpres.dpres.dpres1d() 7th argument (kflag) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ier */
    f2py_success = int_from_pyobj(&ier,ier_capi,"dpres.dpres.dpres1d() 8th argument (ier) can't be converted to int");
  if (f2py_success) {
  /* Processing variable plevel */
  ;
  capi_plevel_intent |= F2PY_INTENT_IN;
  capi_plevel_tmp = array_from_pyobj(NPY_DOUBLE,plevel_Dims,plevel_Rank,capi_plevel_intent,plevel_capi);
  if (capi_plevel_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(dpres_error,"failed in converting 1st argument `plevel' of dpres.dpres.dpres1d to C/Fortran array" );
  } else {
    plevel = (double *)(PyArray_DATA(capi_plevel_tmp));

  /* Processing variable psfc */
    f2py_success = double_from_pyobj(&psfc,psfc_capi,"dpres.dpres.dpres1d() 2nd argument (psfc) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ptop */
    f2py_success = double_from_pyobj(&ptop,ptop_capi,"dpres.dpres.dpres1d() 4th argument (ptop) can't be converted to double");
  if (f2py_success) {
  /* Processing variable pmsg */
    f2py_success = double_from_pyobj(&pmsg,pmsg_capi,"dpres.dpres.dpres1d() 3rd argument (pmsg) can't be converted to double");
  if (f2py_success) {
  /* Processing variable klvl */
  if (klvl_capi == Py_None) klvl = len(plevel); else
    f2py_success = int_from_pyobj(&klvl,klvl_capi,"dpres.dpres.dpres1d() 1st keyword (klvl) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(plevel)>=klvl,"len(plevel)>=klvl","1st keyword klvl","dpres1d:klvl=%d",klvl) {
  /* Processing variable dp */
  dp_Dims[0]=klvl;
  capi_dp_intent |= F2PY_INTENT_IN;
  capi_dp_tmp = array_from_pyobj(NPY_DOUBLE,dp_Dims,dp_Rank,capi_dp_intent,dp_capi);
  if (capi_dp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(dpres_error,"failed in converting 5th argument `dp' of dpres.dpres.dpres1d to C/Fortran array" );
  } else {
    dp = (double *)(PyArray_DATA(capi_dp_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&klvl,plevel,&psfc,&pmsg,&ptop,dp,&iopt,&kflag,&ier);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_dp_tmp!=dp_capi) {
    Py_XDECREF(capi_dp_tmp); }
  }  /*if (capi_dp_tmp == NULL) ... else of dp*/
  /* End of cleaning variable dp */
  } /*CHECKSCALAR(len(plevel)>=klvl)*/
  } /*if (f2py_success) of klvl*/
  /* End of cleaning variable klvl */
  } /*if (f2py_success) of pmsg*/
  /* End of cleaning variable pmsg */
  } /*if (f2py_success) of ptop*/
  /* End of cleaning variable ptop */
  } /*if (f2py_success) of psfc*/
  /* End of cleaning variable psfc */
  if((PyObject *)capi_plevel_tmp!=plevel_capi) {
    Py_XDECREF(capi_plevel_tmp); }
  }  /*if (capi_plevel_tmp == NULL) ... else of plevel*/
  /* End of cleaning variable plevel */
  } /*if (f2py_success) of ier*/
  /* End of cleaning variable ier */
  } /*if (f2py_success) of kflag*/
  /* End of cleaning variable kflag */
  } /*if (f2py_success) of iopt*/
  /* End of cleaning variable iopt */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of dpres1d *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_dpres_def[] = {
  {"dpres1d",-1,{{-1}},0,NULL,(void *)f2py_rout_dpres_dpres_dpres1d,doc_f2py_rout_dpres_dpres_dpres1d},
  {NULL}
};

static void f2py_setup_dpres(char *dpres1d) {
  int i_f2py=0;
  f2py_dpres_def[i_f2py++].data = dpres1d;
}
extern void F_FUNC(f2pyinitdpres,F2PYINITDPRES)(void (*)(char *));
static void f2py_init_dpres(void) {
  F_FUNC(f2pyinitdpres,F2PYINITDPRES)(f2py_setup_dpres);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "dpres",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_dpres(void) {
#else
#define RETVAL
PyMODINIT_FUNC initdpres(void) {
#endif
  int i;
  PyObject *m,*d, *s, *tmp;
#if PY_VERSION_HEX >= 0x03000000
  m = dpres_module = PyModule_Create(&moduledef);
#else
  m = dpres_module = Py_InitModule("dpres", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module dpres (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'dpres' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  dpres --- dpres1d()"".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  dpres_error = PyErr_NewException ("dpres.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "_dpres_error", dpres_error);
  Py_DECREF(dpres_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }

/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "dpres", PyFortranObject_New(f2py_dpres_def,f2py_init_dpres));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"dpres");
#endif
  return RETVAL;
}
#ifdef __cplusplus
}
#endif
