!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitdpres(f2pysetupfunc)
      use dpres, only : dpres1d
      external f2pysetupfunc
      call f2pysetupfunc(dpres1d)
      end subroutine f2pyinitdpres


